### ISSUE TITLE
alpha-values autofixes numeric values

### ISSUE THREAD

**Issue by EvgenyOrekhov** [jeddy3/stylelint-scales#92]
### What steps are needed to reproduce the bug?

Rule config: `"scales/alpha-values": [0, 50, 100]`

Input:

```css
.foo {
  opacity: 0.5;
}
```

### What did you expect to happen?

I expected that autofix will not be applied, since it's a numeric value, not percentage

### What actually happened?

Output:

```css
.foo {
  opacity: 0;
}
```

**Comment by EvgenyOrekhov** [comment]
If I enable `"alpha-value-notation": "percentage"`, `alpha-values` fixer applies first, and I still end up with an invalid value:

```css
.foo {
  opacity: 0%;
}
```
